version: "3"
services:
  spark:
    image: jupyter/pyspark-notebook
    container_name: spark-node
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - .:/home/jovyan/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    container_name: elasticsearch-node
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      nproc: 3000
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 2g
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    container_name: kibana-node
    ports:
      - "5601:5601"
    environment:
      - "xpack.security.enabled=false"

volumes:
  elasticsearch-data:
    driver: local